### PR TITLE
Delete old Docker-related files

### PR DESCRIPTION
**Pull request by mcapuccini**
## Description
Delete old Docker-related configuration files and update docs accordingly (including minor typos fixes).

### CODE REVIEW

**Comment by mcapuccini** [comment]
@Wrede @ahellander ready to review

**Review by Wrede — APPROVED** [review]
Looks good. Andreas is testing.

**Comment by mcapuccini** [comment]
@ahellander this is ready to test again

**Comment by mcapuccini** [comment]
@ahellander works on my Ubuntu workstation

**Review by ahellander — APPROVED** [review]
Seems to work well.

**Pull request merged**
