### PR TITLE
Container monitoring using Prometheus, cAdvisor and Grafana.

### PR DESCRIPTION
**Pull request by sztoor**
## Status

- [ ] Ready

## Description

Describe your changes here to communicate to the maintainers why we should accept this pull request. 
If it fixes a bug or resolves a feature request, be sure to include a link to that issue.

Container monitoring using Prometheus, cAdvisor and Grafana.

## Types of changes

What types of changes does your code introduce to FEDn?

- [ ] New feature

## Checklist

_If you're unsure about any of the items below, don't hesitate to ask. We're here to help! 
This is simply a reminder of what we are going to look for before merging your code._

Not sure

- [x] This pull request is against **develop** branch (not applicable for hotfixes)
- [ ] I have included a link to the issue on GitHub or JIRA (if any)
- [ ] I have included migration files (if there are changes to the model classes)
- [ ] I have read the [CONTRIBUTING](https://github.com/scaleoutsystems/fedn/blob/master/CONTRIBUTING.md) doc
- [ ] I have included tests to complement my changes
- [ ] I have updated the related documentation (if necessary) 
- [ ] I have added a reviewer for this pull request
- [ ] I have added myself as an author for this pull request

## Further comments

Anything else you think we should know before merging your code!

### CODE REVIEW

**Review by ahellander — CHANGES_REQUESTED** [review]
Can we place all config in the "config" folder in the root level of the directory (now it is in fedn/config), i.e. "inside" the module. 

It would be nice if we can make it work on Mac for the pseudo-distributed sandbox.

**Comment by sztoor** [comment]
How I have fixed the config directory in the root.

**Comment by sztoor** [comment]
Now I have created a clear branch for the Fedn monitoring, name "fedn-monitor". We can merge that one and remove this pull request. 

/Salman.

**Comment by sztoor** [comment]
No need to handle this pull request.

**Pull request closed without merging**
