### PR TITLE
Bug/SK-1040 | Fixing numpy version with the MONAI package 

### PR DESCRIPTION
**Pull request by mattiasakesson**
## Description
This PR addresses the bug described in issue SK-1040, which involves fixing the numpy version compatibility with the MONAI package in the FEDn framework.

Updated the numpy version in the requirements to ensure compatibility with MONAI.
Tested the changes to confirm that the issue is resolved.

### CODE REVIEW

**Comment by sztoor** [comment]
This bug is related to numpy version.

**Review by sztoor — APPROVED** [review]
looks good

**Comment by Wrede** [comment]
Need description! Why change numpy version? What issues is being raised with latest numpy?

**Review by ahellander — CHANGES_REQUESTED** [review]
Please add a PR description.

**Review by ahellander — APPROVED** [review]
I added a PR description so we get this merged.

**Pull request merged**
