### PR TITLE
Feature/SK-726 | Refactor APIClient

### PR DESCRIPTION
**Pull request by niklastheman**
# Refactor APIClient

_The api client has been refactored and a couple of new methods has been added. Some methods and parameters has been renamed for consistency. All list_* methods has ben renamed to get_* (plural). All get methods has been refactored to use the new api (/api/v1)_

### Interface after update:

**Clients**
- get_client
- get_clients
- get_client_config
- get_active_clients

**Combiners**
- get_combiner
- get_combiners

**Controllers**
- get_controller_status

**Models**
- get_model
- get_models
- get_active_model (renamed from get_latest_model)
- get_model_trail
- download_model (added)
- set_active_model

**Packages**
- get_package
- get_packages
- get_active_package
- get_package_checksum
- download_package
- set_active_package

**Rounds**
- get_round
- get_rounds

**Sessions**
- get_session
- get_sessions
- get_session_status (added)
- session_is_finished
- start_session

**Statuses**
- get_status (added)
- get_statuses (renamed from get events)

**Validations**
- get_validation (added)
- get_validations

### CODE REVIEW

**Review by ahellander — CHANGES_REQUESTED** [review]
I suggest to rename 'set_model' to 'set_active_model' (to harmonize with 'get_active_model').

**Comment by ahellander** [comment]
Also, 'start_session' seems to be broken: 
Screenshot 2024-03-17 at 13 06 10

**Comment by niklastheman** [comment]
> I suggest to rename 'set_model' to 'set_active_model' (to harmonize with 'get_active_model').

done

**Comment by niklastheman** [comment]
> Also, 'start_session' seems to be broken: Screenshot 2024-03-17 at 13 06 10

done

**Review by ahellander — APPROVED** [review]
Great improvement!

**Pull request merged**
